# Generated by Django 2.0.13 on 2020-08-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLinearResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accuracy', models.CharField(max_length=100)),
                ('precesion', models.CharField(max_length=100)),
                ('recall', models.CharField(max_length=100)),
                ('chitest', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LinearResults',
            },
        ),
    ]
