# Generated by Django 2.0.13 on 2020-08-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlinearresultmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGA2MResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scale', models.CharField(max_length=100)),
                ('deviance', models.CharField(max_length=100)),
                ('pearson_chi2', models.CharField(max_length=100)),
                ('llf', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'GA2MResults',
            },
        ),
    ]
